
% bst_process_data('Subject01', 'D:\data\KLC\average\ec_avg\ASD_P\F103_v1_cb1.set');
% Brainstorm数据处理模板
% 功能：用于导入数据并进行基本处理
% 日期：03-Jan-2024
function bst_process_data(subjectName, rawDataFile)
    % 输入参数：
    % subjectName - 主题名称
    % rawDataFile - 原始数据文件路径

    % 初始化Brainstorm
    brainstorm nogui
    % 获取数据库中所有主题的列表
    sSubjects = bst_get('ProtocolSubjects');

    % 检查主题是否存在
    isSubjectExist = any(strcmp({sSubjects.Subject.Name}, subjectName));

    % 如果主题存在，则先删除现有主题
    if isSubjectExist
        % 获取主题的索引
        iSubject = find(strcmp({sSubjects.Subject.Name}, subjectName));
        
        % 删除主题
        db_delete_subjects(iSubject);
    end
    % 创建新主题
    db_add_subject(subjectName);
    bst_report('Start', []);

    % 导入原始数据
    sFiles = bst_process('CallProcess', 'process_import_data_raw', [], [], ...
        'subjectname',    subjectName, ...
        'datafile',       {rawDataFile, 'EEG-EEGLAB'}, ...
        'channelreplace', 1, ...
        'channelalign',   1, ...
        'evtmode',        'value');
    % 添加 EEG 位置
    sFiles = bst_process('CallProcess', 'process_channel_addloc', sFiles, [], ...
        'channelfile', {'', ''}, ...
        'usedefault',  'ICBM152: BrainProducts EasyCap 64', ...  % 使用默认的头模型
        'fixunits',    1, ...
        'vox2ras',     1, ...
        'mrifile',     {'', ''}, ...
        'fiducials',   []);

    % 对齐默认解剖结构
    sFiles = bst_process('CallProcess', 'process_warp', sFiles, [], ...
        'usedefault', 2, ...  % Warp
        'tolerance',  2);
    % 计算头模型
     sFiles = bst_process('CallProcess', 'process_headmodel', sFiles, [], ...
        'Comment',     '', ...
        'sourcespace', 1, ...  % Cortex surface
        'meg',         3, ...  % Overlapping spheres
        'eeg',         3, ...  % OpenMEEG BEM
        'ecog',        2, ...  % OpenMEEG BEM
        'seeg',        2, ...  % OpenMEEG BEM
        'openmeeg',    struct(...
             'BemFiles',     {{}}, ...
             'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
             'BemCond',      [1, 0.0125, 1], ...
             'BemSelect',    [1, 1, 1], ...
             'isAdjoint',    0, ...
             'isAdaptative', 1, ...
             'isSplit',      0, ...
             'SplitLength',  4000), ...
        'channelfile', '');

     % 计算协方差
    sFiles = bst_process('CallProcess', 'process_noisecov', sFiles, [], ...
        'baseline',       [0, 57.996], ...
        'datatimewindow', [0, 57.996], ...
        'sensortypes',    'MEG, EEG, SEEG, ECOG', ...
        'target',         1, ...  % Noise covariance
        'dcoffset',       1, ...  % Block by block, to avoid effects of slow shifts in data
        'identity',       0, ...
        'copycond',       0, ...
        'copysubj',       0, ...
        'copymatch',      0, ...
        'replacefile',    1);  % Replace


    % 计算源
    sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
        'output',  2, ...  % Kernel only: one per file
        'inverse', struct(...
             'Comment',        'sLORETA: EEG', ...
             'InverseMethod',  'minnorm', ...
             'InverseMeasure', 'sloreta', ...
             'SourceOrient',   {{'fixed'}}, ...
             'Loose',          0.2, ...
             'UseDepth',       0, ...
             'WeightExp',      0.5, ...
             'WeightLimit',    10, ...
             'NoiseMethod',    'reg', ...
             'NoiseReg',       0.1, ...
             'SnrMethod',      'fixed', ...
             'SnrRms',         1e-06, ...
             'SnrFixed',       3, ...
             'ComputeKernel',  1, ...
             'DataTypes',      {{'EEG'}}));
    % Process: Scout time series: [400 scouts]
    sFiles = bst_process('CallProcess', 'process_extract_scout', sFiles, [], ...
        'timewindow',     [0, 57.996], ...
        'scouts',         {'Schaefer_400_7net', {'Cont_Cing_1 L', 'Cont_Cing_1 R', 'Cont_Cing_2 L', 'Cont_Cing_2 R', 'Cont_OFC_1 L', 'Cont_PFCl_1 L', 'Cont_PFCl_1 R', 'Cont_PFCl_10 R', 'Cont_PFCl_11 R', 'Cont_PFCl_12 R', 'Cont_PFCl_13 R', 'Cont_PFCl_14 R', 'Cont_PFCl_15 R', 'Cont_PFCl_2 L', 'Cont_PFCl_2 R', 'Cont_PFCl_3 L', 'Cont_PFCl_3 R', 'Cont_PFCl_4 L', 'Cont_PFCl_4 R', 'Cont_PFCl_5 L', 'Cont_PFCl_5 R', 'Cont_PFCl_6 L', 'Cont_PFCl_6 R', 'Cont_PFCl_7 L', 'Cont_PFCl_7 R', 'Cont_PFCl_8 L', 'Cont_PFCl_8 R', 'Cont_PFCl_9 R', 'Cont_PFCmp_1 L', 'Cont_PFCmp_1 R', 'Cont_PFCmp_2 R', 'Cont_PFCv_1 L', 'Cont_PFCv_1 R', 'Cont_Par_1 L', 'Cont_Par_1 R', 'Cont_Par_2 L', 'Cont_Par_2 R', 'Cont_Par_3 L', 'Cont_Par_3 R', 'Cont_Par_4 L', 'Cont_Par_4 R', 'Cont_Par_5 L', 'Cont_Par_5 R', 'Cont_Par_6 L', 'Cont_Par_6 R', 'Cont_Temp_1 L', 'Cont_Temp_1 R', 'Cont_Temp_2 R', 'Cont_pCun_1 L', 'Cont_pCun_1 R', 'Cont_pCun_2 L', 'Cont_pCun_2 R', 'Default_PFC_1 L', 'Default_PFC_10 L', 'Default_PFC_11 L', 'Default_PFC_12 L', 'Default_PFC_13 L', 'Default_PFC_14 L', 'Default_PFC_15 L', 'Default_PFC_16 L', 'Default_PFC_17 L', 'Default_PFC_18 L', 'Default_PFC_19 L', 'Default_PFC_2 L', 'Default_PFC_20 L', 'Default_PFC_21 L', 'Default_PFC_22 L', 'Default_PFC_23 L', 'Default_PFC_24 L', 'Default_PFC_3 L', 'Default_PFC_4 L', 'Default_PFC_5 L', 'Default_PFC_6 L', 'Default_PFC_7 L', 'Default_PFC_8 L', 'Default_PFC_9 L', 'Default_PFCdPFCm_1 R', 'Default_PFCdPFCm_10 R', 'Default_PFCdPFCm_11 R', 'Default_PFCdPFCm_12 R', 'Default_PFCdPFCm_13 R', 'Default_PFCdPFCm_2 R', 'Default_PFCdPFCm_3 R', 'Default_PFCdPFCm_4 R', 'Default_PFCdPFCm_5 R', 'Default_PFCdPFCm_6 R', 'Default_PFCdPFCm_7 R', 'Default_PFCdPFCm_8 R', 'Default_PFCdPFCm_9 R', 'Default_PFCv_1 R', 'Default_PFCv_2 R', 'Default_PFCv_3 R', 'Default_PFCv_4 R', 'Default_Par_1 L', 'Default_Par_1 R', 'Default_Par_2 L', 'Default_Par_2 R', 'Default_Par_3 L', 'Default_Par_3 R', 'Default_Par_4 L', 'Default_Par_4 R', 'Default_Par_5 L', 'Default_Par_5 R', 'Default_Par_6 L', 'Default_Par_7 L', 'Default_Temp_1 L', 'Default_Temp_1 R', 'Default_Temp_10 L', 'Default_Temp_2 L', 'Default_Temp_2 R', 'Default_Temp_3 L', 'Default_Temp_3 R', 'Default_Temp_4 L', 'Default_Temp_4 R', 'Default_Temp_5 L', 'Default_Temp_5 R', 'Default_Temp_6 L', 'Default_Temp_6 R', 'Default_Temp_7 L', 'Default_Temp_7 R', 'Default_Temp_8 L', 'Default_Temp_8 R', 'Default_Temp_9 L', 'Default_pCunPCC_1 L', 'Default_pCunPCC_1 R', 'Default_pCunPCC_10 L', 'Default_pCunPCC_11 L', 'Default_pCunPCC_2 L', 'Default_pCunPCC_2 R', 'Default_pCunPCC_3 L', 'Default_pCunPCC_3 R', 'Default_pCunPCC_4 L', 'Default_pCunPCC_4 R', 'Default_pCunPCC_5 L', 'Default_pCunPCC_5 R', 'Default_pCunPCC_6 L', 'Default_pCunPCC_6 R', 'Default_pCunPCC_7 L', 'Default_pCunPCC_7 R', 'Default_pCunPCC_8 L', 'Default_pCunPCC_8 R', 'Default_pCunPCC_9 L', 'Default_pCunPCC_9 R', 'DorsAttn_FEF_1 L', 'DorsAttn_FEF_1 R', 'DorsAttn_FEF_2 L', 'DorsAttn_FEF_2 R', 'DorsAttn_FEF_3 L', 'DorsAttn_FEF_3 R', 'DorsAttn_FEF_4 L', 'DorsAttn_Post_1 L', 'DorsAttn_Post_1 R', 'DorsAttn_Post_10 L', 'DorsAttn_Post_10 R', 'DorsAttn_Post_11 L', 'DorsAttn_Post_11 R', 'DorsAttn_Post_12 L', 'DorsAttn_Post_12 R', 'DorsAttn_Post_13 L', 'DorsAttn_Post_13 R', 'DorsAttn_Post_14 L', 'DorsAttn_Post_14 R', 'DorsAttn_Post_15 L', 'DorsAttn_Post_15 R', 'DorsAttn_Post_16 L', 'DorsAttn_Post_16 R', 'DorsAttn_Post_17 L', 'DorsAttn_Post_17 R', 'DorsAttn_Post_18 R', 'DorsAttn_Post_19 R', 'DorsAttn_Post_2 L', 'DorsAttn_Post_2 R', 'DorsAttn_Post_3 L', 'DorsAttn_Post_3 R', 'DorsAttn_Post_4 L', 'DorsAttn_Post_4 R', 'DorsAttn_Post_5 L', 'DorsAttn_Post_5 R', 'DorsAttn_Post_6 L', 'DorsAttn_Post_6 R', 'DorsAttn_Post_7 L', 'DorsAttn_Post_7 R', 'DorsAttn_Post_8 L', 'DorsAttn_Post_8 R', 'DorsAttn_Post_9 L', 'DorsAttn_Post_9 R', 'DorsAttn_PrCv_1 L', 'DorsAttn_PrCv_1 R', 'DorsAttn_PrCv_2 L', 'Limbic_OFC_1 L', 'Limbic_OFC_1 R', 'Limbic_OFC_2 L', 'Limbic_OFC_2 R', 'Limbic_OFC_3 L', 'Limbic_OFC_3 R', 'Limbic_OFC_4 L', 'Limbic_OFC_4 R', 'Limbic_OFC_5 L', 'Limbic_OFC_5 R', 'Limbic_OFC_6 R', 'Limbic_TempPole_1 L', 'Limbic_TempPole_1 R', 'Limbic_TempPole_2 L', 'Limbic_TempPole_2 R', 'Limbic_TempPole_3 L', 'Limbic_TempPole_3 R', 'Limbic_TempPole_4 L', 'Limbic_TempPole_4 R', 'Limbic_TempPole_5 L', 'Limbic_TempPole_5 R', 'Limbic_TempPole_6 L', 'Limbic_TempPole_6 R', 'Limbic_TempPole_7 L', 'Limbic_TempPole_7 R', 'Limbic_TempPole_8 L', 'SalVentAttn_FrOperIns_1 L', 'SalVentAttn_FrOperIns_1 R', 'SalVentAttn_FrOperIns_2 L', 'SalVentAttn_FrOperIns_2 R', 'SalVentAttn_FrOperIns_3 L', 'SalVentAttn_FrOperIns_3 R', 'SalVentAttn_FrOperIns_4 L', 'SalVentAttn_FrOperIns_4 R', 'SalVentAttn_FrOperIns_5 L', 'SalVentAttn_FrOperIns_5 R', 'SalVentAttn_FrOperIns_6 L', 'SalVentAttn_FrOperIns_6 R', 'SalVentAttn_FrOperIns_7 L', 'SalVentAttn_FrOperIns_7 R', 'SalVentAttn_FrOperIns_8 L', 'SalVentAttn_FrOperIns_8 R', 'SalVentAttn_FrOperIns_9 L', 'SalVentAttn_Med_1 L', 'SalVentAttn_Med_1 R', 'SalVentAttn_Med_2 L', 'SalVentAttn_Med_2 R', 'SalVentAttn_Med_3 L', 'SalVentAttn_Med_3 R', 'SalVentAttn_Med_4 L', 'SalVentAttn_Med_4 R', 'SalVentAttn_Med_5 L', 'SalVentAttn_Med_5 R', 'SalVentAttn_Med_6 L', 'SalVentAttn_Med_6 R', 'SalVentAttn_Med_7 L', 'SalVentAttn_Med_7 R', 'SalVentAttn_Med_8 R', 'SalVentAttn_PFCl_1 L', 'SalVentAttn_PFCl_1 R', 'SalVentAttn_ParOper_1 L', 'SalVentAttn_ParOper_2 L', 'SalVentAttn_ParOper_3 L', 'SalVentAttn_ParOper_4 L', 'SalVentAttn_PrC_1 R', 'SalVentAttn_TempOccPar_1 R', 'SalVentAttn_TempOccPar_2 R', 'SalVentAttn_TempOccPar_3 R', 'SalVentAttn_TempOccPar_4 R', 'SalVentAttn_TempOccPar_5 R', 'SalVentAttn_TempOccPar_6 R', 'SalVentAttn_TempOccPar_7 R', 'SalVentAttn_TempOcc_1 L', 'SomMot_1 L', 'SomMot_1 R', 'SomMot_10 L', 'SomMot_10 R', 'SomMot_11 L', 'SomMot_11 R', 'SomMot_12 L', 'SomMot_12 R', 'SomMot_13 L', 'SomMot_13 R', 'SomMot_14 L', 'SomMot_14 R', 'SomMot_15 L', 'SomMot_15 R', 'SomMot_16 L', 'SomMot_16 R', 'SomMot_17 L', 'SomMot_17 R', 'SomMot_18 L', 'SomMot_18 R', 'SomMot_19 L', 'SomMot_19 R', 'SomMot_2 L', 'SomMot_2 R', 'SomMot_20 L', 'SomMot_20 R', 'SomMot_21 L', 'SomMot_21 R', 'SomMot_22 L', 'SomMot_22 R', 'SomMot_23 L', 'SomMot_23 R', 'SomMot_24 L', 'SomMot_24 R', 'SomMot_25 L', 'SomMot_25 R', 'SomMot_26 L', 'SomMot_26 R', 'SomMot_27 L', 'SomMot_27 R', 'SomMot_28 L', 'SomMot_28 R', 'SomMot_29 L', 'SomMot_29 R', 'SomMot_3 L', 'SomMot_3 R', 'SomMot_30 L', 'SomMot_30 R', 'SomMot_31 L', 'SomMot_31 R', 'SomMot_32 L', 'SomMot_32 R', 'SomMot_33 L', 'SomMot_33 R', 'SomMot_34 L', 'SomMot_34 R', 'SomMot_35 L', 'SomMot_35 R', 'SomMot_36 L', 'SomMot_36 R', 'SomMot_37 L', 'SomMot_37 R', 'SomMot_38 R', 'SomMot_39 R', 'SomMot_4 L', 'SomMot_4 R', 'SomMot_40 R', 'SomMot_5 L', 'SomMot_5 R', 'SomMot_6 L', 'SomMot_6 R', 'SomMot_7 L', 'SomMot_7 R', 'SomMot_8 L', 'SomMot_8 R', 'SomMot_9 L', 'SomMot_9 R', 'Vis_1 L', 'Vis_1 R', 'Vis_10 L', 'Vis_10 R', 'Vis_11 L', 'Vis_11 R', 'Vis_12 L', 'Vis_12 R', 'Vis_13 L', 'Vis_13 R', 'Vis_14 L', 'Vis_14 R', 'Vis_15 L', 'Vis_15 R', 'Vis_16 L', 'Vis_16 R', 'Vis_17 L', 'Vis_17 R', 'Vis_18 L', 'Vis_18 R', 'Vis_19 L', 'Vis_19 R', 'Vis_2 L', 'Vis_2 R', 'Vis_20 L', 'Vis_20 R', 'Vis_21 L', 'Vis_21 R', 'Vis_22 L', 'Vis_22 R', 'Vis_23 L', 'Vis_23 R', 'Vis_24 L', 'Vis_24 R', 'Vis_25 L', 'Vis_25 R', 'Vis_26 L', 'Vis_26 R', 'Vis_27 L', 'Vis_27 R', 'Vis_28 L', 'Vis_28 R', 'Vis_29 L', 'Vis_29 R', 'Vis_3 L', 'Vis_3 R', 'Vis_30 L', 'Vis_30 R', 'Vis_31 L', 'Vis_4 L', 'Vis_4 R', 'Vis_5 L', 'Vis_5 R', 'Vis_6 L', 'Vis_6 R', 'Vis_7 L', 'Vis_7 R', 'Vis_8 L', 'Vis_8 R', 'Vis_9 L', 'Vis_9 R'}}, ...
        'flatten',        1, ...
        'scoutfunc',      'mean', ...  % Mean
        'pcaedit',        struct(...
             'Method',         'pca', ...
             'Baseline',       [-0.1, 0], ...
             'DataTimeWindow', [0, 1], ...
             'RemoveDcOffset', 'file'), ...
        'isflip',         1, ...
        'isnorm',         0, ...
        'concatenate',    1, ...
        'save',           1, ...
        'addrowcomment',  1, ...
        'addfilecomment', []);

    % 保存并显示报告
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    
% 加载Scout time series数据
    DataMat = in_bst(sFiles(1).FileName);
    ScoutData = DataMat.Value;
    % 获取rawDataFile的文件名，去掉后缀.set
% 获取rawDataFile的目录路径和文件名
    [rawDataFilePath, rawFileName, ~] = fileparts(rawDataFile);
    
    % 构建保存文件的完整路径
    saveFileName = fullfile(rawDataFilePath, sprintf('scout_400_%s.mat', rawFileName));
    
    % 保存Scout time series数据到MAT文件
    save(saveFileName, 'ScoutData');
    % 可选：导出、发送报告等
    % bst_report('Export', ReportFile, ExportDir);
    % bst_report('Email', ReportFile, username, to, subject, isFullReport);

    % 清理临时文件
    % gui_brainstorm('EmptyTempFolder');
end
